## Ejercicio 1
Crea una función que determine qué debe hacer el usuario, según la hora del día. El usuario debe ingresar por consola qué hora es (slo la hora, no los minutos), y el programa le debe decir qué está agendado a esa hora. La casuística es la siguiente:

* Si es entre las 0 y las 8, print "Durmiendo"
* Si es entre las 9 y las 18, print "Trabajando"
* Si es entre las 19 y las 21, print "Clase"
* Si es entre las 22 y las 24, print "Descanso"
* En cualquier otro caso, print "Transporte o error"

Implementa mediante sentencias `if/elif/else`.

In [ ]:
def schedule():
    hora = int(input("Qué hora es? Me vale solo la hora en punto, no los minutos."))
    if hora >= 0 and hora <= 8:
        print("Durmiendo")
    elif hora >= 9 and hora <= 18:
        print("Trabajando")
    elif hora >= 19 and hora <= 21:
        print("Clase")
    elif hora >= 22 and hora <= 24:
        print("Descanso")
    else:
        print("Transporte o error")
schedule()

Durmiendo

## Ejercicio 2
En este ejercicio vamos a implementar un calculador de precios de casas muy sencillo. Tenemos las siguientes variables:

> superficie
>
> distrito

Implementa mediante sentencias `if/elif/else` la siguiente casuística:

1. Si el distrito es "Moncloa" o "Centro", y además la superficie es superior a 100 metros cuadrados, el precio de la casa es de 1000
2. Si el distrito es "Salamanca", y además la superficie de la casa es al menos de 150 metros, el precio de la casa es de 1500
3. Si el distrito no es "Retiro" y la superficie está entre 60 y 80 metros, el precio es de 600
4. En cualquier otro caso, el precio será de 0

Crea la calculadora de precios mediante una función que le pida al usuario el distrito y la superficie mediante input. Utiliza los bucles y el control de flujos que consideres adecuados. 

Sé creativo/a con el bot, the sky is the limit!

In [4]:
def calculadorInmobiliaria():
    while True:
        distrito = input("En que distrito estas")
        while True:
            superficie = input("Cuantos metros tiene?")
            if superficie.isdigit():
                superficie = int(superficie)
                break
            else:
                print("Pon un numero correcto")

        if (distrito.lower() == 'moncloa' or distrito.lower() == 'centro') and superficie > 100:
            precio = 1000
            print("El precio es ", precio, "€")
        elif (distrito.lower() == 'salamanca') and superficie >= 150:
            precio = 1500
            print("El precio es ", precio, "€")
        elif (distrito.lower() != 'retiro') and (superficie >= 60 and superficie <= 80):
            precio = 600
            print("El precio es ", precio, "€")
        else:
            precio = 0
            print("El precio es ", precio, "€")
        print(distrito, superficie)
        pregunta = input("Quieres ver otra casa? Pulsa 'YES' para continuar viendo casas (Y)...")
        if pregunta == 'Y':
            print("de acuerdo")
        else:
            print("Muchas gracias")
            break
calculadorInmobiliaria()

El precio es  1000 €
Moncloa 1500
de acuerdo
El precio es  0 €
Reitro 600
Muchas gracias

## Ejercicio 3
En este ejercicio vamos a realizar un programa muy parecido. Para este caso queremos que se cumplan las siguientes condiciones:

1. Si el distrito es "Retiro", comprueba si si la superficie es mayor de 100 metros cuadrados. En tal caso, que imprima un precio de 1000, y si no, de 500, mas el mensaje "Distrito con $$$".
2. Si NO es Retiro, deberá ser un 25% menos, e imprimit "Distrito pobre". 

TIP: Hay que usar `ifs` anidados.

Crea tu código siempre con funciones, para que lo puedas reutilizar luego!

In [ ]:
def calculadorInmobiliaria2():
    distrito = input("¿En qué distrito estás? ")
    
    while True:
        superficie_str = input("¿Cuántos metros tiene? ")
        if superficie_str.isdigit():
            superficie = int(superficie_str)
            break 
        else:
            print("Por favor, introduce un número correcto para la superficie.")
            
    precio = 0
    distrito_formato = distrito.lower().strip() 
    
    # Condición 1: Si el distrito es 
    if distrito_formato == "retiro":
        if superficie > 100:
            precio = 1000
        else:
            precio = 500

        print(f"Distrito: {distrito}")
        print(f"El precio es de {precio} €")
        
    # Condición 2: Si NO es Retiro 
    else:
        if superficie > 100:
            precio = 1000 * 0.75
        else:
            precio = 500 * 0.75
        
        # Imprimir el resultado para otros distritos
        print("Distrito pobre")
        print(f"El precio es de {precio} €") 

calculadorInmobiliaria2()

Distrito pobre
El precio es de 375.0 €

## Ejercicio 4
Escribe una función que le pida al usuario un número del 1 al 100. 

Tienes una variable `lista = [2, 3, 4, 5, 6]`.

El programa debe comprobar que el usuario introduce un número válido. Y luego lo siguiente: 
- Si el número es entre 1 y 30, debe ser multiplicado por la lista de números. El programa debe recorrer la lista e imprimir por pantalla cada elemento de la lista multiplicado por el número uno bajo el otro, separados con este separador: "|"
- Si el número es mayor a 30 y menor a 60, debe ser elevado por esa lista. 
- Si el número es igual o mayor a 60 e igual o menor que 100, debe dividirse por los números de esa lista. 
- Si es mayor a 100, debe lanzar mensaje de error. Esto lo puedes hacer con ifs, o practicar el try/except!

Recuerda documentar las funciones, de a poco ir implementando buenas prácticas!

In [11]:
def procesarNumero():
    """
    Pide un número al usuario (1-100) y realiza diferentes operaciones
    (multiplicación, potencia, división) según el rango del número.
    """
    lista = [2, 3, 4, 5, 6]
    
    try:
        numero = int(input("Dime un número del 1 al 100: "))
    except ValueError:
        print("Error: Por favor, introduce un número entero válido.")
        return

    print("-" * 30)

    # Condición de error: Mayor a 100 o menor a 1
    if numero > 100 or numero < 1:
        print("Error: El número debe estar en el rango del 1 al 100.")
        
    # Condición 1: Multiplicación (1 <= numero <= 30)
    elif 1 <= numero <= 30:
        print(f"Caso: Multiplicación (Número {numero} x Elemento)")
        for elemento in lista:
            resultado = numero * elemento
            print(f"{resultado}|")

    # Condición 2: Potencia (30 < numero < 60)
    elif numero > 30 and numero < 60:
        print(f"Caso: Potencia (Número {numero} ** Elemento)")
        for elemento in lista:
            # Usamos el operador ** para elevar
            resultado = numero ** elemento
            print(f"{resultado}|")

    # Condición 3: División (60 <= numero <= 100)
    elif 60 <= numero <= 100:
        print(f"Caso: División (Número {numero} / Elemento)")
        for elemento in lista:
            # La división siempre resulta en un float (/)
            resultado = numero / elemento
            # Formateamos a 2 decimales para la presentación
            print(f"{resultado:.2f}|") 

# Llamada a la función
procesarNumero()

------------------------------
Caso: Potencia (Número 50 ** Elemento)
2500|
125000|
6250000|
312500000|
15625000000|

## Ejercicio 5
Utiliza la función "range" e imprime por pantalla cada número del -10 al -1. En ese orden. Consulta [la documentación](https://www.w3schools.com/python/ref_func_range.asp) de `range`

In [14]:
for numero in range (-10, 0):
    print(numero, end=" ")

-10 -9 -8 -7 -6 -5 -4 -3 -2 -1

## Ejercicio 6
Dada la siguiente lista:

> list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]

Implementa un programa que los recorra e imprima por pantalla todos los divisibles por 5. Si nos encontramos con alguno que sea mayor que 150, detener el bucle.

In [15]:
list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
for num in list1:
    if num > 150:
        break
    if num % 5 == 0:
        print(num)

15
55
75
150

## Ejercicio 7
Escribe un programa en Python que imprima por pantalla todos los números divisibles por 5 y divisibles por 7, dentro del rango de valores (150, 350)

In [7]:
for num in range (150, 351):
    if num % 5 == 0 and num % 7 == 0: # if num % (5*7) == 0:
        print(num)

175
210
245
280
315
350

## Ejercicio 8
Implementa un programa que imprima por pantalla el siguiente patrón

5 4 3 2 1 

4 3 2 1 

3 2 1 

2 1 

1

NOTA: NO hay lineas en blanco entre una línea y otra.

In [16]:
start = 5
stop = 0
for num in range (start, stop, -1): #start, stop, step. Si el step es negativo, baja, si es postivo, sube. E indica de cuánto en cuánto 
    for num in range (num, stop, -1):
        print(num, end = " ")
    print()

5 4 3 2 1
4 3 2 1
3 2 1
2 1
1

## Ejercicio 9
En este ejercicio vamos a crear un pequeño juego. Se trata de intentar adivinar un numero del 1 al 5. Tenemos dos intentos para acertar. Pasos a seguir:

1. Ya viene implementado cómo obtener un número aleatorio del 1 al 5
2. Tendrás que declarar en una variable el numero de vidas, y mediante un bucle while, comprobar que todavia quedan vidas.
3. Dentro del bucle, obtener el valor del usuario y comprobar si es ese el numero a adivinar. Si no, actualizar las vidas.
4. Si acertamos, salimos del bucle e imprimimos por pantalla "You win". Y si perdemos también salimos del bucle, pero en este caso imprimimos por pantalla "You lose".

TIP: te puede resultar útil usar la sentencia `else` cuando acabe el bucle `while`. Lo que haya dentro de ese `else` se ejecutará una vez acabe la ejecución del `while`. Lo podrás usar para cuando pierdas.

In [28]:
import random

def adivinaElNumero():
    """
    Pequeño juego para adivinar un número del 1 al 5 en dos intentos.
    """

    numero_secreto = random.randint(1, 5)

    vidas = 2
    
    print("¡Bienvenido al juego! Tienes 2 intentos para adivinar un número entre 1 y 5.")

    while vidas > 0:

        print(f"\nTe quedan {vidas} intento(s).")
        
        try:
            # Obtener el valor del usuario
            intento = int(input("Introduce tu número (1-5): "))
        except ValueError:
            print("Entrada inválida. Por favor, introduce un número entero.")
            continue # Vuelve al inicio del bucle sin gastar una vida
            
        # Validación básica del rango
        if not (1 <= intento <= 5):
            print("Número fuera de rango. Debe ser entre 1 y 5.")
            continue # Vuelve al inicio del bucle sin gastar una vida

        # Comprobar si es el número a adivinar
        if intento == numero_secreto:
            # Si acertamos, salimos del bucle e imprimimos "You win"
            print(f"\n¡Felicidades! El número era {numero_secreto}.")
            print("You Has ganado")
            break  # Rompe el bucle while
        else:
            # Si no, actualizamos las vidas
            vidas -= 1
            if vidas > 0:
                print("Incorrecto. ¡Sigue intentándolo!")
                
    # 4. Sentencia else del bucle while (para cuando se pierde)
    # Este bloque 'else' solo se ejecuta si el 'while' termina
    # por la condición (vidas <= 0), no por un 'break'.
    else:
        print(f"\nGame Over. El número secreto era {numero_secreto}.")
        print("Hasta la vista baby")

# Llamada a la función para iniciar el juego
adivinaElNumero()

¡Bienvenido al juego! Tienes 2 intentos para adivinar un número entre 1 y 5.

Te quedan 2 intento(s).
Incorrecto. ¡Sigue intentándolo!

Te quedan 1 intento(s).

Game Over. El número secreto era 2.
Hasta la vista baby

### Ejercicio 10
Crea una función para ver qué toca hacer hoy. Pide al usuario que introduzca un número del 1 al 7 por consola, que representará un día de la semana (Lunes a Domingo). Implementa la siguiente casuística con una función:

- Si el número es 6 o 7, imprime "Hoy es fin de semana, vete de fiesta!"
- Si está entre 1 y 4, imprime "Hoy toca currar todo el día"
- Si el número es 5, imprime "Hoy trabaja por la mañana, y estudia por la tarde"
- En cualquier otro caso, imprime "La semana tiene solo 7 días!"

In [44]:
def comprobarDiaSemana():
    """
    Pide un número del 1 al 7 y clasifica el día de la semana.
"""
    dia = int(input("Dime en qué día de la semana estás, y te diré qué te toca hacer :) "))
    if dia == 6 or dia == 7:
        print("Hoy es fin de semana, vete de fiesta!")
    elif 1 <= dia <= 4:
        print("Hoy toca currar todo el día")
    elif dia == 5:
        print("Hoy trabaja por la mañana, y estudia por la tarde")
    else:
        print("La semana tiene solo 7 días")
comprobarDiaSemana()

Hoy es fin de semana, vete de fiesta!


### Ejercicio 11
Vamos a crear un clasificador de vehículos. Declara las siguientes variables:

> peso  
> tipo

Implementa la siguiente casuística:

1. Si el tipo es "Camión" y el peso es superior a 5000 kg, el vehículo es "Vehículo pesado"
2. Si el tipo es "Coche" y el peso es más de 2000, el vehículo es "Vehículo pesadito"
3. Si el tipo es "Coche" y el peso está entre 1000 kg y 2000 kg, el vehículo es "Vehículo ligero"
4. Si el tipo es "Moto" y el peso es mayor a 500, el vehículo es "Vehículo ligero".
5. Si el tipo no es "Moto" y el peso es menor de 500 kg, el vehículo es "Vehículo muy ligero"
6. En cualquier otro caso, clasifica el vehículo como "Sin clasificación"

In [46]:
def clasificadorVehiculosSimple():
    """
    Clasifica un vehículo según su tipo y peso.
    Versión simple: solo pide la entrada una vez.
    """

    tipo = input("¿Qué tipo de vehículo tienes? (Camión, Coche, Moto): ").strip().capitalize()
    
    try:
        peso_str = input("¿Cuánto pesa tu vehículo (en kg)? ")
        peso = int(peso_str)
    except ValueError:
        print("Error: El peso debe ser un número entero. Saliendo del clasificador.")
        return 

    print("-" * 30)
    
    clasificacion = "Sin clasificación" 

    if tipo == "Camión" and peso > 5000:
        clasificacion = "Vehículo pesado"

    elif tipo == "Coche" and peso > 2000:
        clasificacion = "Vehículo pesadito"

    elif tipo == "Coche" and 1000 <= peso <= 2000:
        clasificacion = "Vehículo ligero"

    elif tipo == "Moto" and peso > 500:
        clasificacion = "Vehículo ligero"

    elif tipo != "Moto" and peso < 500:
        clasificacion = "Vehículo muy ligero"


    print(f"Tipo: {tipo}, Peso: {peso} kg")
    print(f"Clasificación: {clasificacion}")


clasificadorVehiculosSimple()

------------------------------
Tipo: 100, Peso: 500 kg
Clasificación: Sin clasificación

### Ejercicio 12
Vamos a crear un sistema que determine si un alumno tiene derecho a una beca. Declara las siguientes variables:

> nota  
> ingresos

Implementa la siguiente lógica:

1. Si la nota es igual o mayor a 8, imprime "Posible candidato"
2. Si es así, comprueba si los ingresos son menores de 20000, en cuyo caso imprime "Beca aprobada". Si los ingresos son superiores, imprime "No cumple los requisitos económicos"
3. Si la nota no es mayor de 8, imprime "No cumple los requisitos académicos"

In [54]:
def clasificadorBeca():
    """
    Determina si un alumno tiene derecho a una beca basándose en la nota
    y los ingresos, utilizando ifs anidados.
    """
    nota = int(input("Qué nota tienes?"))
    if nota >= 8:
        print("Posible candidato")
        ingresos = int(input("Qué ingresos tiene tu unidad familiar?"))
        if ingresos < 20000:
            print("Beca aprobada")
        else:
            print("No cumple los requisitos económicos")
    else:
        print("No cumple los requisitos académicos")
clasificadorBeca()

Posible candidato
No cumple los requisitos económicos

### Ejercicio 13
Escribe un programa que tenga dos variables: un string (pedido al usuario a través de input) y una lista de strings `["Python", "java", "codigo", "ejemplo", "Mundo", "azul"]`. El programa debe recorrer la lista e imprimir por pantalla cada elemento de la lista concatenado con el string, pero: 
- Si la palabra dada por el usuario empieza con vocal, deberás convertirla a MAYÚSCULAS. 
- Caso contrario, debe empezar con mayúsculas y luego minúsculas
Luego comprueba
- Si la palabra tiene más de 4 letras, deberás eliminar las letras "r", "s", "l" o "m" que tenga.   
- Si tiene 4 letras o menos, agrega una carita felis ":)" luego de ésta.

In [5]:
def procesarTexto():
    """
    Pide un string al usuario, aplica formato y eliminación de caracteres,
    luego concatena el resultado con cada elemento de la lista.
    """
    lista_de_palabras = ["Python", "java", "codigo", "ejemplo", "Mundo", "azul"]
    VOCALES = 'aeiouAEIOU'
    # CORRECCIÓN CLAVE: Incluimos mayúsculas en los caracteres a eliminar
    CARACTERES_A_ELIMINAR = 'rslmRSLM' 

    string_usuario = input("Introduce una palabra: ").strip()

    if not string_usuario:
        print("No se introdujo ninguna palabra. Saliendo del programa.")
        return

    # --- 1. Formateo del String del Usuario ---

    palabra_formateada = ""
    
    if string_usuario[0].lower() in VOCALES.lower():
        # Caso 1: Empieza con vocal -> Convertir a MAYÚSCULAS
        palabra_formateada = string_usuario.upper()
    else:
        # Caso 2: No empieza con vocal -> Primera letra mayúscula, resto minúsculas
        palabra_formateada = string_usuario.capitalize()

    # --- 2. Aplicar eliminación de letras o agregar carita feliz ---
    
    if len(palabra_formateada) > 4:
        # Eliminar las letras "r", "s", "l", "m" (tanto mayúsculas como minúsculas)
        palabra_modificada = palabra_formateada
        for char_a_eliminar in CARACTERES_A_ELIMINAR:
            # Aplicar el reemplazo
            palabra_modificada = palabra_modificada.replace(char_a_eliminar, '')
        
        palabra_final_usuario = palabra_modificada
        
    else:
        # Si tiene 4 letras o menos, agrega una carita felis ":)"
        palabra_final_usuario = palabra_formateada + ":)"

    print("\n--- Resultados del Procesamiento ---")
    print(f"Palabra inicial del usuario: {string_usuario}")
    print(f"Palabra del usuario procesada: {palabra_final_usuario}")
    print("-" * 35)
    
    # --- 3. Recorrer la lista y concatenar ---
    
    for elemento in lista_de_palabras:
        
        # Concatenar el elemento de la lista con la palabra del usuario ya FINALIZADA
        resultado = elemento + " " + palabra_final_usuario
        
        print(resultado)

# Llamada a la función
procesarTexto()

--- Resultados del Procesamiento ---
Palabra inicial del usuario: carisma
Palabra del usuario procesada: Caia
-----------------------------------
Python Caia
java Caia
codigo Caia
ejemplo Caia
Mundo Caia
azul Caia

### Ejercicio 14
Dada la siguiente lista:

> list2 = [25, 35, 45, 55, 65, 75, 85, 95, 105, 115]

Implementa un programa que los recorra e imprima por pantalla solo los divisibles por 15. Si nos encontramos con uno mayor que 100, detén el bucle.

In [7]:
list2 = [25, 35, 45, 55, 65, 75, 85, 95, 105, 115]

for num in list2:
    if num > 100:
        break
    if num % 15 == 0:
        print(num)

45
75

### Ejercicio 15
Escribe un programa que imprima por pantalla todos los números que sean múltiplos de 3 y de 4, dentro del rango de valores (50, 150).

In [8]:
for i in range(50, 151):
    if i % 3 == 0 and i % 4 == 0:
        print(i)

60
72
84
96
108
120
132
144

### Ejercicio 16
Implementa un programa que imprima por pantalla el siguiente patrón:

```
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5
```

NOTA: No debe haber espacios al final de cada línea.

In [9]:
for i in range(1, 6):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

### Ejercicio 17
En este ejercicio vamos a crear otro juego sencillo. Se trata de intentar adivinar una palabra secreta entre dos intentos. Pasos a seguir:

1. Declara la palabra secreta en una variable
2. Declara una variable para el número de intentos, e implementa un bucle `while` que verifique que aún hay intentos restantes.
3. Dentro del bucle, solicita al usuario que introduzca una palabra y compárala con la palabra secreta.
4. Si el usuario acierta, imprime "Has ganado" y sal del bucle.
5. Si se acaban los intentos sin acertar, imprime "Lo siento, has perdido".

In [10]:
def adivinaLaPalabra():
    """
    Juego para adivinar una palabra secreta en dos intentos.
    """

    palabra_secreta = "Python"

    intentos_restantes = 2
    
    print("¡Adivina la Palabra Secreta!")
    print(f"Tienes {intentos_restantes} intentos. (Pista: Es un lenguaje de programación muy popular)")

    while intentos_restantes > 0:
        
        print(f"\nIntento(s) restante(s): {intentos_restantes}")
        

        intento = input("Introduce tu palabra: ").strip() 
        

        if intento.lower() == palabra_secreta.lower():

            print("\n¡Felicidades, has acertado!")
            print("Has ganado")
            break
        else:

            intentos_restantes -= 1
            if intentos_restantes > 0:
                print("Incorrecto. Inténtalo de nuevo.")

    else:

        print("\nGame Over.")
        print(f"Lo siento, has perdido. La palabra secreta era: {palabra_secreta}")

adivinaLaPalabra()

¡Adivina la Palabra Secreta!
Tienes 2 intentos. (Pista: Es un lenguaje de programación muy popular)

Intento(s) restante(s): 2
Incorrecto. Inténtalo de nuevo.

Intento(s) restante(s): 1

Game Over.
Lo siento, has perdido. La palabra secreta era: Python

### Ejercicio 18
Crea un programa que divida dos números introducidos por el usuario. Utiliza `try` y `except` para manejar posibles errores de división por cero. Si se produce un error, imprime "No se puede dividir por cero". Si no, imprime el resultado.

In [12]:
try:
    numerador = int(input("Introduce el numerador: "))
    denominador = int(input("Introduce el denominador: "))
    resultado = numerador / denominador
except ZeroDivisionError:
    print("No se puede dividir por cero")
else:
    print(f"Resultado: {resultado}")

Resultado: 0.7777777777777778

## Ejercicio 19
Dada la siguiente lista:
> ```ejer_1 = [1,2,3,4,5]```

Inviértela para que quede de la siguiente manera. Prueba 2 o 3 formas distintas de hacerlo.
> ```ejer_1 = [5,4,3,2,1]```

In [13]:
ejer_1 = [1,2,3,4,5]
ejer_1.sort(reverse=True)
print(ejer_1)

[5, 4, 3, 2, 1]

In [14]:
ejer_1 = [1,2,3,4,5]
ejer_1 = ejer_1[::-1]
print(ejer_1)

[5, 4, 3, 2, 1]

In [15]:
ejer_1 = [1,2,3,4,5]
ejer_1.reverse()
print(ejer_1)

[5, 4, 3, 2, 1]

## Ejercicio 20
Eleva todos los elementos de la lista al cuadrado
> ```ejer_2 = [1,2,3,4,5]```

Cómo lo harías con numpy?

In [16]:
ejer_2 = [1,2,3,4,5]
for i in ejer_2:
    print(i**2)

1
4
9
16
25

In [17]:
import numpy as np
ejer2 = np.array(ejer_2)
print(ejer2 **2)

[ 1  4  9 16 25]

## Ejercicio 21
Crea una lista nueva con todas las combinaciones de las siguientes dos listas:
> ```ejer_21_1 = ["Hola", "amigo"]```
>
> ```ejer_21_2 = ["Que", "tal"]```

Obten el siguiente output:

```['Hola Que', 'Hola tal', 'amigo Que', 'amigo tal']```

In [18]:
frase = []
ejer_21_1 = ["Hola", "amigo"]
ejer_21_2 = ["Que", "tal"]

for p1 in ejer_21_1:
    for p2 in ejer_21_2:
        combinacion = p1 + " " + p2
        frase.append(combinacion)

print(frase)

['Hola Que', 'Hola tal', 'amigo Que', 'amigo tal']

## Ejercicio 22
Dada la siguiente lista, encuentra por el índice el valor 45 y sustitúyelo por el 0
> ```ejer_22 = [20, 47, 19, 29, 45, 67, 78, 90]```

In [19]:
ejer_22 = [20, 47, 19, 29, 45, 67, 78, 90]

# 1. Encontrar el índice del valor 45
try:
    indice_a_sustituir = ejer_22.index(45)
    
    # 2. Sustituir el valor en ese índice por 0
    ejer_22[indice_a_sustituir] = 0
    
    print(f"Lista original: [20, 47, 19, 29, 45, 67, 78, 90]")
    print(f"Índice del valor 45: {indice_a_sustituir}")
    print(f"Lista final: {ejer_22}")

except ValueError:
    print("El valor 45 no se encuentra en la lista.")

Lista original: [20, 47, 19, 29, 45, 67, 78, 90]
Índice del valor 45: 4
Lista final: [20, 47, 19, 29, 0, 67, 78, 90]

## Ejercicio 23
Dada la siguiente lista, elimina todos los valores iguales a 3
> ```ejer_23 = [3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3]```

TIP: No intentes eliminar elementos sobre la lista que estás iterando. Haz una copia con `ejer_5.copy()`.

In [20]:
ejer_23 = [3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3]

# Creamos una copia de la lista para iterar
lista_a_iterar = ejer_23.copy()

print(f"Lista original: {ejer_23}")

for valor in lista_a_iterar:
    if valor == 3:
        # Eliminamos el valor 3 de la lista original
        ejer_23.remove(valor)

print(f"Lista final:{ejer_23}")

Lista original: [3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3]
Lista final:[20, 47, 19, 29, 45, 67, 78, 90]

## Ejercicio 24
1. Crea una tupla con 3 elementos
2. Crea otra tupla con un elemento y comprueba su tipo
3. Crea una tupla con elementos de diferentes tipos
4. Imprime por pantalla el primer y último elemento de la tupla del apartado 3. Usa `len` para el último
5. Añade un elemento a la tupla del apartado 3.
6. Eliminar un elemento de la tupla del apartado 5, que se encuentre más o menos en la mitad.
7. Convierte la tupla del apartado 5 en una lista

In [21]:
## Ejercicio 24: Operaciones con Tuplas

# 1. Crea una tupla con 3 elementos
tupla_1 = (10, 20, 30)
print(f"1. Tupla de 3 elementos: {tupla_1}")

# 2. Crea otra tupla con un elemento y comprueba su tipo
# NOTA: Se requiere la coma (,) al final para que Python la reconozca como tupla.
tupla_un_elemento = (42,)
print(f"2. Tupla de 1 elemento: {tupla_un_elemento}")
print(f"   Tipo de la variable: {type(tupla_un_elemento)}")

# 3. Crea una tupla con elementos de diferentes tipos
tupla_diferentes_tipos = ("Manzana", 3.14, True, 2025)
print(f"3. Tupla de diferentes tipos: {tupla_diferentes_tipos}")

# 4. Imprime por pantalla el primer y último elemento de la tupla del apartado 3. Usa len para el último
primer_elemento = tupla_diferentes_tipos[0]
# El índice del último elemento es len(tupla) - 1
ultimo_elemento = tupla_diferentes_tipos[len(tupla_diferentes_tipos) - 1] 
print(f"4. Primer elemento: {primer_elemento}")
print(f"   Último elemento (usando len): {ultimo_elemento}")
print("-" * 30)

# 5. Añade un elemento a la tupla del apartado 3.
# Debido a la inmutabilidad, convertimos a lista, añadimos y volvemos a tupla.
tupla_a_lista = list(tupla_diferentes_tipos)
tupla_a_lista.append("NuevoElemento")
tupla_con_anadido = tuple(tupla_a_lista) # Esta es la nueva tupla del apartado 5
print(f"5. Tupla con elemento añadido (por conversión): {tupla_con_anadido}")

# 6. Eliminar un elemento de la tupla del apartado 5, que se encuentre más o menos en la mitad.
# Repetimos el proceso: lista -> eliminar -> tupla.
tupla_a_lista_2 = list(tupla_con_anadido)
longitud = len(tupla_a_lista_2)
# Calculamos el índice "medio" (usando división entera //)
indice_medio = longitud // 2 

# Eliminamos el elemento en el índice medio
elemento_eliminado = tupla_a_lista_2.pop(indice_medio) 
tupla_sin_elemento = tuple(tupla_a_lista_2)

print(f"6. Elemento eliminado (índice {indice_medio}): {elemento_eliminado}")
print(f"   Tupla sin elemento medio: {tupla_sin_elemento}")

# 7. Convierte la tupla del apartado 5 en una lista
# Usamos la tupla generada en el paso 5: tupla_con_anadido
lista_final = list(tupla_con_anadido) 
print(f"7. Tupla del apartado 5 convertida a lista: {lista_final}")
print(f"   Tipo de la variable: {type(lista_final)}")

1. Tupla de 3 elementos: (10, 20, 30)
2. Tupla de 1 elemento: (42,)
   Tipo de la variable: <class 'tuple'>
3. Tupla de diferentes tipos: ('Manzana', 3.14, True, 2025)
4. Primer elemento: Manzana
   Último elemento (usando len): 2025
------------------------------
5. Tupla con elemento añadido (por conversión): ('Manzana', 3.14, True, 2025, 'NuevoElemento')
6. Elemento eliminado (índice 2): True
   Tupla sin elemento medio: ('Manzana', 3.14, 2025, 'NuevoElemento')
7. Tupla del apartado 5 convertida a lista: ['Manzana', 3.14, True, 2025, 'NuevoElemento']
   Tipo de la variable: <class 'list'>

## Ejercicio 25
Concatena todos los elementos de la tupla en un único string. Para ello utiliza el metodo `.join()` de los Strings
> ```ejer_25 = ("cien", "cañones", "por", "banda")```

Resultado: `cien cañones por banda`

In [23]:
ejer_25 = ("cien", "cañones", "por", "banda")
resultado_25 = " ".join(ejer_25)
print(f"Ejercicio 25: {resultado_25}")

Ejercicio 25: cien cañones por banda

## Ejercicio 26
Obten el tercer elemento de la siguiente tupla, y el tercero empezando por el final
> ```ejer_26 = (3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3)```

In [25]:
ejer_26 = (3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3)

tercer_elemento = ejer_26[2]
tercero_por_el_final = ejer_26[-3]
print(f"Ejercicio 26 - Tercer elemento: {tercer_elemento}, Tercero por el final: {tercero_por_el_final}")

Ejercicio 26 - Tercer elemento: 3, Tercero por el final: 90

## Ejercicio 27
1. ¿Cuántas veces se repite el 3 en la siguiente tupla?
2. Crea una tupla nueva con los elementos desde la posición 5 a la 10.
3. ¿Cuántos elementos tiene la tupla `ejer_27`?
4. Comprueba si el numero 60 está en la tupla
> ```ejer_27 = (3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3, 5, 2, 4, 7, 9, 4, 2, 4, 3, 3, 4, 6, 7)```

In [27]:
ejer_27 = (3, 20, 3, 47, 19, 3, 29, 45, 67, 78, 90, 3, 3, 5, 2, 4, 7, 9, 4, 2, 4, 3, 3, 4, 6, 7)

veces_3 = ejer_27.count(3)

tupla_slice = ejer_27[5:11] 

longitud_9 = len(ejer_27)

contiene_60 = 60 in ejer_27
print(f"Ejercicio 27 - 1. Veces 3: {veces_3}")
print(f"Ejercicio 27 - 2. Tupla slice: {tupla_slice}")
print(f"Ejercicio 27 - 3. Longitud: {longitud_9}")
print(f"Ejercicio 27 - 4. Contiene 60: {contiene_60}")

Ejercicio 27 - 1. Veces 3: 7
Ejercicio 27 - 2. Tupla slice: (3, 29, 45, 67, 78, 90)
Ejercicio 27 - 3. Longitud: 26
Ejercicio 27 - 4. Contiene 60: False

## Ejercicio 28
1. Convierte la tupla del ejercicio 27 en una lista
2. Convierte la tupla del ejercicio 27 en un set
3. Convierte la tupla del ejercicio 27 en un diccionario. Usa también los índices

In [28]:
# 1. Convierte la tupla del ejercicio 27 en una lista
lista_ejer_27 = list(ejer_27)
# 2. Convierte la tupla del ejercicio 27 en un set
set_ejer_27 = set(ejer_27)
# 3. Convierte la tupla del ejercicio 27 en un diccionario. Usa también los índices
dict_ejer_27 = {index: valor for index, valor in enumerate(ejer_27)}
print(f"Ejercicio 28 - 1. Lista: {lista_ejer_27[:5]}...")
print(f"Ejercicio 28 - 2. Set: {set_ejer_27}")
print(f"Ejercicio 28 - 3. Diccionario (primeros 5): {list(dict_ejer_27.items())[:5]}...")

Ejercicio 28 - 1. Lista: [3, 20, 3, 47, 19]...
Ejercicio 28 - 2. Set: {2, 3, 67, 5, 4, 7, 6, 9, 45, 78, 47, 19, 20, 90, 29}
Ejercicio 28 - 3. Diccionario (primeros 5): [(0, 3), (1, 20), (2, 3), (3, 47), (4, 19)]...

## Ejercicio 29
Convierte la siguiente lista en un diccionario
> ```ejer_29 = [("x", 1), ("x", 2), ("x", 3), ("y", 1), ("y", 2), ("z", 1)]```

TIP: Puedes usar dos variables de control en un bucle `for`. Una por cada valor de las tuplas. Prueba si existe alguna otra forma más sencilla.

In [37]:
ejer_29 = [("x", 1), ("x", 2), ("x", 3), ("y", 1), ("y", 2), ("z", 1)]

In [38]:
diccionario_bucle = {}
for clave, valor in ejer_29:

    diccionario_bucle[clave] = valor

print(f"Ejercicio 29 con bucle: {diccionario_bucle}")

Ejercicio 29 con bucle: {'x': 3, 'y': 2, 'z': 1}

In [39]:
dict_ejer_29 = dict(ejer_29)
print(f"Ejercicio 29: {dict_ejer_29}")

Ejercicio 29: {'x': 3, 'y': 2, 'z': 1}

## Ejercicio 30
1. Crea una lista ordenada ascendente con las claves del diccionario
2. Crea otra lista ordenada descendente con los valores
3. Añade una nueva clave/valor
4. Busca la clave "2" dentro del diccionario
5. Itera la clave y el valor del diccionario con un único for
> ```ejer_12 = {4:78, 2:98, 8:234, 5:29}```

In [43]:
ejer_30 = {4:78, 2:98, 8:234, 5:29}

claves_asc = sorted(ejer_30.keys())
print(f"Ej. 30 - 1. Claves ascendentes: {claves_asc}")

valores_desc = sorted(ejer_30.values(), reverse=True)
print(f"Ej. 30 - 2. Valores descendentes: {valores_desc}")

ejer_30[10] = 500
print(f"Ej. 30 - 3. Diccionario con añadido: {ejer_30}")

contiene_clave_2 = 2 in ejer_30
print(f"Ej. 30 - 4. Contiene clave 2: {contiene_clave_2}")

print("Ej. 30 - 5. Iteración clave/valor:")
for clave, valor in ejer_30.items():
    print(f"Clave: {clave}, Valor: {valor}")

Ej. 30 - 1. Claves ascendentes: [2, 4, 5, 8]
Ej. 30 - 2. Valores descendentes: [234, 98, 78, 29]
Ej. 30 - 3. Diccionario con añadido: {4: 78, 2: 98, 8: 234, 5: 29, 10: 500}
Ej. 30 - 4. Contiene clave 2: True
Ej. 30 - 5. Iteración clave/valor:
Clave: 4, Valor: 78
Clave: 2, Valor: 98
Clave: 8, Valor: 234
Clave: 5, Valor: 29
Clave: 10, Valor: 500

## Ejercicio 31
Junta ambos diccionarios. Para ello, utiliza `update`
> ```ejer_31_1 = {1: 11, 2: 22}```
>
> ```ejer_31_2 = {3: 33, 4: 44}```

In [45]:
ejer_31_1 = {1: 11, 2: 22}
ejer_31_2 = {3: 33, 4: 44}
ejer_31_1.update(ejer_31_2)
diccionario_unido = ejer_31_1
print(f"Ejercicio 31: {diccionario_unido}")

Ejercicio 31: {1: 11, 2: 22, 3: 33, 4: 44}

## Ejercicio 32
Suma todos los valores del dicionario
> ```ejer_32 = {1: 11, 2: 22, 3: 33, 4: 44, 5: 55}```

In [46]:
ejer_32 = {1: 11, 2: 22, 3: 33, 4: 44, 5: 55}
suma_valores = sum(ejer_32.values())
print(f"Ejercicio 32: {suma_valores}")

Ejercicio 32: 165

## Ejercicio 33
Multiplica todos los valores del diccionario
> ```ejer_33 = {1: 11, 2: 22, 3: 33, 4: 44, 5: 55}```

In [47]:
ejer_33 = {1: 11, 2: 22, 3: 33, 4: 44, 5: 55}
multiplicacion = 1
for valor in ejer_33.values():
    multiplicacion *= valor
print(f"Ejercicio 33: {multiplicacion}")

Ejercicio 33: 19326120

## Ejercicio 34
1. Crea un set de tres elementos: 5, 10, 25. Haz print()
2. Añade un cuarto. Haz print()
3. Elimina el último elemento añadido. Haz print()
4. Elimina el elemento 10, si está presente. Usa `discard()`. Haz print()

In [54]:
set_32 = {5, 10, 25}
print(set_32)
set_32.add(35)
print(set_32)
set_32.remove(35) 
print(set_32)
set_32.discard(10)
print(f"Ejercicio 34: {set_32}")

{25, 10, 5}
{25, 10, 35, 5}
{25, 10, 5}
Ejercicio 34: {25, 5}

# Ejercicios funciones

Crea funciones en un archivo aparte .py e impórtalas y úsalas aquí. 
## Ejercicio 35
Escribe una función que reciba un número y devuelva ese número elevado al cuadrado.

In [58]:
def conversor (num):
    num = num*num 
    return f"Tu numero es: {num}"

In [59]:
# Ej: 
# from funciones import conversor 
conversor(16)

'Tu numero es: 256'

## Ejercicio 36
En un ejercicio de flujos de control másarriba, creábamos una pirámide invertida de números desde el 5. Crea una función que replique el comportamiento de la pirámide, y utiliza un único parámetro de entrada de la función para determinar el número de filas de la pirámide.

In [60]:
def piramide(filas):
    for num in range(filas, 0, -1): 
        for num in range(num, 0, -1): 
            print(num, end=" ") 
        print()
piramide(5)

5 4 3 2 1
4 3 2 1
3 2 1
2 1
1

## Ejercicio 37
Escribe una función que compare dos números. La función tiene dos argumentos y hay tres salidas posibles: que sean iguales, que el primero sea  mayor que el segundo, o que el segundo sea mayor que el primero

In [62]:
def compara (num1, num2):
    if num1 == num2:
        return f'{num1} y {num2} son iguales'
    if num1 > num2:
        return f'{num1} es mayor que {num2}'
    if num1 < num2:
        return f'{num2} es mayor a {num1}'

compara ((3*3), (20/5))

'9 es mayor que 4.0'

## Ejercicio 38
Escribe una función que sea un contador de letras. En el primer argumento tienes que introducir un texto, y el segundo que sea una letra que contar. La función tiene que devolver un entero con el número de veces que aparece esa letra, tanto mayúscula, como minúscula

In [63]:
def contar_letras (texto, letra):
    if letra in texto:
       x = texto.count(letra)
       return x

contar_letras('Oid mortales el grito sagrado, libertad, libertad, libertad', "a")

6

## Ejercicio 39
Escribe una función que tenga un único argumento, un string. La salida de la función tiene que ser un diccionario con el conteo de todas las letras de ese string, siendo la clave la letra y el valor el conteo.

In [64]:
dic_frase = {}
def diccio_cuenta (frase):
    for letra in frase:
        if letra in dic_frase:
            dic_frase[letra] = dic_frase[letra] + 1
        else:
            dic_frase[letra] = 1
    return dic_frase

diccio_cuenta('Heladeria')

{'H': 1, 'e': 2, 'l': 1, 'a': 2, 'd': 1, 'r': 1, 'i': 1}

## Ejercicio 40
Escribir una función que añada o elimine elementos en una lista. La función necesita los siguientes argumentos:
* lista: la lista donde se añadirán o eliminarán los elementos
* comando: "add" o "remove"
* elemento: Por defecto es None.

Tendrá como salida la lista

In [65]:
def agrega_elimina (lista, comando, elemento = None):
    if comando == "add":
        lista.append(elemento)
        return lista
    elif comando == "remove":
        if elemento in lista:
            lista.remove(elemento)
            return lista
        else:
            return "Ese elemento no esta en la lista"

agrega_elimina(['Jose', 'Pedro', 'Juan'], "remove", 'Juan')

['Jose', 'Pedro']

## Ejercicio 41
Crea una función que reciba un número arbitrario de palabras, y devuelva una frase completa, separando las palabras con espacios.

In [67]:
def palabras(*args):
    return " ".join(args)

palabras('arbol', 'mono', 'iglesia', 'lluvia')

'arbol mono iglesia lluvia'

## Ejercicio 42
Escribe un programa que obtenga el enésimo número de la [serie de Fibonacci](https://es.wikipedia.org/wiki/Sucesi%C3%B3n_de_Fibonacci). Tienes que crear una función recursiva con un único argumento.

```Python
fibonacci(2) = 1
fibonacci(4) = 3
fibonacci(5) = 5
fibonacci(8) = 21
```

fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)

In [68]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
    
fibonacci(8)

21

## Ejercicio 43
Define en una única celda las siguientes funciones:
* Función que calcule el área de un cuadrado
* Función que calcule el área de un triángulo
* Función que calcule el área de un círculo

En otra celda, calcular el area de:
* Dos círculos de radio 10 + un triángulo de base 3 y altura 7
* Un cuadrado de lado = 10 + 3 círculos (uno de radio = 4 y los otros dos de radio = 6) + 5 triángulos de base = 2 + altura = 4

In [132]:
import math

In [133]:
def area_cuadrado(lado):
    area = lado * lado
    return area

def area_triangulo(base, altura):
    area = (base * altura)/2
    return area 

def area_circulo(radio):
    area = math.pi * (radio **2)
    return area

In [134]:
resultado1 = (area_circulo(10)) * 2 + area_triangulo(3, 7)
print(resultado1)
resultado2 = area_cuadrado(10) + area_circulo(4) + (area_circulo(6) * 2) + (area_triangulo (2, 4)*5)
print(resultado2)

638.8185307179587
396.46015351590177

# Importar funciones

## Ejercicio 44
Vamos a crear una clase para representar una biblioteca. La clase debe permitir gestionar libros y su disponibilidad.

* Nombre de la clase: "Biblioteca"
* Atributos comunes:
    * Tipo: "Pública"
    * Horario: "09:00 - 20:00"
* Atributos propios de cada biblioteca:
    * Nombre - String
    * Dirección - String
    * Lista de libros disponibles - Lista de strings
    * Lista de libros prestados - Lista de strings
* Método para añadir un libro a la lista de disponibles
* Método para prestar un libro, que lo elimine de la lista de disponibles y lo añada a la de prestados
* Método para devolver un libro, que lo elimine de la lista de prestados y lo añada a la de disponibles
* Método que imprime el nombre de la biblioteca y su dirección
* Método que devuelve la cantidad total de libros en la biblioteca (sumando disponibles y prestados)

Se pide:
1. Implementar la clase "Biblioteca"
2. Crear dos bibliotecas con datos inventados
3. Añadir libros y prestar algunos de ellos
4. Verificar la cantidad total de libros en ambas bibliotecas
5. Imprimir el nombre y dirección de todas las bibliotecas que contengan la palabra "Central"

In [74]:
class Biblioteca:
    tipo = "Pública"
    horario = "09:00 - 20:00"
    
    def __init__(self, nombre: str, direccion: str):
        self.nombre = nombre
        self.direccion = direccion
        self.libros_disponibles = []
        self.libros_prestados = []
        
    def agregar_libro(self, libro: str):
        self.libros_disponibles.append(libro)
        print(f"'{libro}' añadido a {self.nombre}.")
        
    def prestar_libro(self, libro: str) -> bool:
        """Presta un libro (Disponible -> Prestado)."""
        if libro in self.libros_disponibles:
            self.libros_disponibles.remove(libro)
            self.libros_prestados.append(libro)
            print(f"'{libro}' prestado de {self.nombre}.")
            return True
        else:
            print(f"Error: '{libro}' no está disponible en {self.nombre}.")
            return False
    
    def devolver_libro(self, libro: str) -> bool:
        """Devuelve un libro (Prestado -> Disponible)."""
        if libro in self.libros_prestados:
            self.libros_prestados.remove(libro)
            self.libros_disponibles.append(libro)
            print(f"'{libro}' devuelto a {self.nombre}.")
            return True
        else:
            print(f"Error: '{libro}' no estaba prestado de {self.nombre}.")
            return False
    
    def imprimir_informacion(self):
        """Imprime el nombre de la biblioteca y su dirección."""
        print(f"Biblioteca: {self.nombre}, Dirección: {self.direccion}")
    
    def cantidad_total_libros(self) -> int:
        """Devuelve la cantidad total de libros (disponibles + prestados)."""
        return len(self.libros_disponibles) + len(self.libros_prestados)

# Ejemplo de uso
# 2. Crear dos bibliotecas con datos inventados
biblioteca1 = Biblioteca("Biblioteca Central Madrid", "Avenida del Sol 45")
biblioteca2 = Biblioteca("Biblioteca de Barrio (Gracia)", "Calle Luna 32")
biblioteca3 = Biblioteca("Biblioteca Central de Sevilla", "Plaza Mayor s/n") 

# Lista para manejar las bibliotecas
bibliotecas = [biblioteca1, biblioteca2, biblioteca3]

print("\n--- 3. Añadir libros y prestar algunos de ellos ---")
# Añadir libros a biblioteca 1
biblioteca1.agregar_libro("El Quijote")
biblioteca1.agregar_libro("Cien Años de Soledad")
biblioteca1.agregar_libro("1984")
biblioteca1.prestar_libro("El Quijote")
biblioteca1.prestar_libro("El Quijote") #

# Añadir libros a biblioteca 2
biblioteca2.agregar_libro("Rebelión en la Granja")
biblioteca2.agregar_libro("Orgullo y Prejuicio")
biblioteca2.prestar_libro("Rebelión en la Granja")

# Añadir libros a biblioteca 3
biblioteca3.agregar_libro("La Sombra del Viento")

print("\n--- Verificación de Devolución ---")
biblioteca1.devolver_libro("1984") 
biblioteca1.devolver_libro("El Quijote") 

print("\n--- 4. Verificar la cantidad total de libros ---")
for biblio in bibliotecas:
    print(f"Total de libros en {biblio.nombre}: {biblio.cantidad_total_libros()}")

print("\n--- 5. Imprimir el nombre y dirección de todas las bibliotecas que contengan la palabra 'Central' ---")
for biblio in bibliotecas:
    if "Central" in biblio.nombre:
        biblio.imprimir_informacion()

--- 3. Añadir libros y prestar algunos de ellos ---
'El Quijote' añadido a Biblioteca Central Madrid.
'Cien Años de Soledad' añadido a Biblioteca Central Madrid.
'1984' añadido a Biblioteca Central Madrid.
'El Quijote' prestado de Biblioteca Central Madrid.
Error: 'El Quijote' no está disponible en Biblioteca Central Madrid.
'Rebelión en la Granja' añadido a Biblioteca de Barrio (Gracia).
'Orgullo y Prejuicio' añadido a Biblioteca de Barrio (Gracia).
'Rebelión en la Granja' prestado de Biblioteca de Barrio (Gracia).
'La Sombra del Viento' añadido a Biblioteca Central de Sevilla.

--- Verificación de Devolución ---
Error: '1984' no estaba prestado de Biblioteca Central Madrid.
'El Quijote' devuelto a Biblioteca Central Madrid.

--- 4. Verificar la cantidad total de libros ---
Total de libros en Biblioteca Central Madrid: 3
Total de libros en Biblioteca de Barrio (Gracia): 2
Total de libros en Biblioteca Central de Sevilla: 1

--- 5. Imprimir el nombre y dirección de todas las bibliotecas que contengan la palabra 'Central' ---
Biblioteca: Biblioteca Central Madrid, Dirección: Avenida del Sol 45
Biblioteca: Biblioteca Central de Sevilla, Dirección: Plaza Mayor s/n

## Ejercicio 45
Vamos a modelar un vehículo que se puede alquilar, como en una empresa de alquiler de coches.

* Nombre de la clase: "VehículoAlquiler"
* Atributos comunes:
    * Disponible: True
* Atributos propios de cada vehículo:
    * Marca - String
    * Modelo - String
    * Año - int
    * Kilometraje - float
* Método para alquilar el vehículo, que cambie el atributo `Disponible` a False
* Método para devolver el vehículo, que cambie `Disponible` a True y aumente el kilometraje con el valor que se pasa como argumento
* Método para obtener la descripción del vehículo (marca, modelo y año)
* Método que calcula el precio del alquiler según los kilómetros recorridos, con una tarifa fija de 0.50€/km

Se pide:
1. Implementar la clase "VehículoAlquiler"
2. Crear tres vehículos y alquilar dos de ellos
3. Devolver uno de los vehículos con un kilometraje añadido
4. Imprimir la descripción de todos los vehículos disponibles
5. Calcular el precio del alquiler de uno de los vehículos devueltos

In [76]:
class VehículoAlquiler:

    def __init__(self, marca: str, modelo: str, año: int, kilometraje: float):
        self.marca = marca
        self.modelo = modelo
        self.año = año
        self.kilometraje = kilometraje
        # El estado 'disponible' es un atributo propio de cada instancia.
        self.disponible = True 

    def alquilar(self):
        if self.disponible:
            self.disponible = False
            print(f"{self.obtener_descripcion()} ha sido ALQUILADO.")
        else:
            print(f"Error: {self.obtener_descripcion()} NO está disponible para alquilar.")

    def devolver(self, kilometraje_aumentado: float):
        if not self.disponible:
            self.disponible = True
            self.kilometraje += kilometraje_aumentado
            print(f"{self.obtener_descripcion()} ha sido DEVUELTO. Kilometraje total: {self.kilometraje:.2f} km.")

        else:
            print(f"Error: {self.obtener_descripcion()} ya estaba disponible.")

    def obtener_descripcion(self) -> str:
        return f"{self.marca} {self.modelo} ({self.año})"

    def calcular_precio_alquiler(self, kilometros_recorridos: float) -> float:
        TARIFA = 0.50
        return kilometros_recorridos * TARIFA


print("\n--- 2. Creación y Alquiler ---")
# 2. Crear tres vehículos
vehiculo1 = VehículoAlquiler("Toyota", "Corolla", 2021, 15000)
vehiculo2 = VehículoAlquiler("Ford", "Focus", 2019, 30000)
vehiculo3 = VehículoAlquiler("BMW", "X5", 2022, 5000)

flota = [vehiculo1, vehiculo2, vehiculo3]


vehiculo1.alquilar() 
vehiculo2.alquilar()

print("\n--- 3. Devolver un vehículo ---")

km_recorridos_v1 = 120.5
vehiculo1.devolver(km_recorridos_v1)


print("\n--- 4. Imprimir la descripción de todos los vehículos disponibles ---")
for vehiculo in flota:
    if vehiculo.disponible:
        print(f"DISPONIBLE: {vehiculo.obtener_descripcion()}")

print("\n--- 5. Calcular el precio del alquiler de uno de los vehículos devueltos ---")

precio_v1 = vehiculo1.calcular_precio_alquiler(km_recorridos_v1)
print(f"El precio del alquiler de {vehiculo1.obtener_descripcion()} por {km_recorridos_v1} km es: {precio_v1:.2f}€")

--- 2. Creación y Alquiler ---
Toyota Corolla (2021) ha sido ALQUILADO.
Ford Focus (2019) ha sido ALQUILADO.

--- 3. Devolver un vehículo ---
Toyota Corolla (2021) ha sido DEVUELTO. Kilometraje total: 15120.50 km.

--- 4. Imprimir la descripción de todos los vehículos disponibles ---
DISPONIBLE: Toyota Corolla (2021)
DISPONIBLE: BMW X5 (2022)

--- 5. Calcular el precio del alquiler de uno de los vehículos devueltos ---
El precio del alquiler de Toyota Corolla (2021) por 120.5 km es: 60.25€

## Ejercicio 46
Vamos a modelar un sistema de gestión de cursos para una plataforma educativa.

* Nombre de la clase: "Curso"
* Atributos comunes:
    * Modalidad: "Online"
* Atributos propios de cada curso:
    * Nombre - String
    * Profesor - String
    * Número de lecciones - int
    * Estudiantes inscritos - Lista de strings (nombres de los estudiantes)
* Método para inscribir un estudiante, que añade un nombre a la lista de inscritos
* Método para calcular el número total de estudiantes inscritos
* Método que imprime un resumen del curso con su nombre y profesor
* Método para cambiar al profesor del curso

Se pide:
1. Implementar la clase "Curso"
2. Crear dos cursos con información inventada
3. Inscribir a algunos estudiantes en cada curso
4. Cambiar el profesor de uno de los cursos
5. Imprimir el resumen de todos los cursos con más de 3 estudiantes inscritos

In [77]:
class Curso:
    modalidad = "Online"


    def __init__(self, nombre: str, profesor: str, num_lecciones: int):
        self.nombre = nombre
        self.profesor = profesor
        self.num_lecciones = num_lecciones
        self.estudiantes_inscritos = [] 

    def inscribir_estudiante(self, estudiante: str):
        """Añade un nombre a la lista de estudiantes inscritos."""
        self.estudiantes_inscritos.append(estudiante)
        
    def cantidad_estudiantes(self) -> int:
        """Calcula el número total de estudiantes inscritos."""
        return len(self.estudiantes_inscritos)

    def resumen_curso(self) -> str:
        """Imprime un resumen del curso con su nombre y profesor."""
        return f"Curso: {self.nombre}, Profesor: {self.profesor} (Modalidad: {self.modalidad})"
        
    def cambiar_profesor(self, nuevo_profesor: str):
        """Cambia al profesor del curso."""
        self.profesor = nuevo_profesor
        print(f"El profesor de '{self.nombre}' ha cambiado a {nuevo_profesor}.")


print("\n--- 2. Crear dos cursos ---")
curso1 = Curso("Python para Principiantes", "María García", 10)
curso2 = Curso("Introducción a la IA", "Carlos Pérez", 12)
curso3 = Curso("Desarrollo Web Avanzado", "Andrea Lozano", 15)

cursos = [curso1, curso2, curso3]

print("\n--- 3. Inscribir a algunos estudiantes ---")

curso1.inscribir_estudiante("Ana")
curso1.inscribir_estudiante("Luis")
curso1.inscribir_estudiante("Clara")
curso1.inscribir_estudiante("Jorge")


curso2.inscribir_estudiante("Pedro")
curso2.inscribir_estudiante("Sofía")


curso3.inscribir_estudiante("Elena")
curso3.inscribir_estudiante("David")
curso3.inscribir_estudiante("Marta")
curso3.inscribir_estudiante("Javier")
curso3.inscribir_estudiante("Nerea")

print(f"Curso 1 tiene: {curso1.cantidad_estudiantes()} estudiantes.")
print(f"Curso 2 tiene: {curso2.cantidad_estudiantes()} estudiantes.")

print("\n--- 4. Cambiar el profesor de uno de los cursos ---")
curso1.cambiar_profesor("Laura Martínez")

print("\n--- 5. Imprimir el resumen de todos los cursos con más de 3 estudiantes inscritos ---")

print("Cursos con más de 3 estudiantes:")
for curso in cursos:
    if curso.cantidad_estudiantes() > 3:
        print(curso.resumen_curso())

--- 2. Crear dos cursos ---

--- 3. Inscribir a algunos estudiantes ---
Curso 1 tiene: 4 estudiantes.
Curso 2 tiene: 2 estudiantes.

--- 4. Cambiar el profesor de uno de los cursos ---
El profesor de 'Python para Principiantes' ha cambiado a Laura Martínez.

--- 5. Imprimir el resumen de todos los cursos con más de 3 estudiantes inscritos ---
Cursos con más de 3 estudiantes:
Curso: Python para Principiantes, Profesor: Laura Martínez (Modalidad: Online)
Curso: Desarrollo Web Avanzado, Profesor: Andrea Lozano (Modalidad: Online)

## Ejercicio 47
Vamos a crear una clase para modelar una cuenta bancaria.

* Nombre de la clase: "CuentaBancaria"
* Atributos comunes:
    * Moneda: "EUR"
* Atributos propios de cada cuenta:
    * Número de cuenta - String
    * Titular - String
    * Saldo - float
* Método para realizar un depósito, que aumente el saldo con un valor pasado como argumento
* Método para retirar una cantidad, que disminuya el saldo si hay fondos suficientes, sino devuelve un mensaje indicando falta de fondos
* Método para obtener el saldo actual
* Método para transferir dinero a otra cuenta (pasada como argumento), que disminuya el saldo si hay fondos suficientes y aumente el saldo de la cuenta destino

Se pide:
1. Implementar la clase "CuentaBancaria"
2. Crear dos cuentas con información inventada
3. Realizar depósitos y retirar dinero de las cuentas
4. Transferir dinero de una cuenta a otra
5. Imprimir el saldo de ambas cuentas después de la transferencia

In [78]:
class CuentaBancaria:
    # Atributo común (atributo de clase)
    moneda = "EUR"

    def __init__(self, numero_cuenta: str, titular: str, saldo: float):
        self.numero_cuenta = numero_cuenta
        self.titular = titular
        self.saldo = saldo

    def depositar(self, cantidad: float) -> bool:
        """Realiza un depósito y aumenta el saldo."""
        if cantidad > 0:
            self.saldo += cantidad
            print(f"[DEPÓSITO OK] Saldo de {self.titular} (N° {self.numero_cuenta[-4:]}) aumentado en {cantidad:.2f} {self.moneda}.")
            return True
        else:
            print("[ERROR] La cantidad a depositar debe ser positiva.")
            return False

    def retirar(self, cantidad: float) -> bool:
        """Retira una cantidad si hay fondos suficientes."""
        if cantidad > self.saldo:
            print(f"[ERROR RETIRO] Fondos insuficientes para {self.titular}. Saldo actual: {self.saldo:.2f} {self.moneda}.")
            return False
        if cantidad <= 0:
            print("[ERROR RETIRO] La cantidad a retirar debe ser positiva.")
            return False
        
        self.saldo -= cantidad
        print(f"[RETIRO OK] {self.titular} retiró {cantidad:.2f} {self.moneda}. Saldo restante: {self.saldo:.2f} {self.moneda}.")
        return True

    def obtener_saldo(self) -> float:
        """Devuelve el saldo actual."""
        return self.saldo

    def transferir(self, otra_cuenta: 'CuentaBancaria', cantidad: float) -> bool:
        """Transfiere dinero a otra cuenta si hay fondos suficientes."""
        
        if cantidad > self.saldo:
            print(f"[ERROR TRANSFERENCIA] {self.titular} no tiene suficientes fondos para transferir {cantidad:.2f} {self.moneda}.")
            return False
        if cantidad <= 0:
            print("[ERROR TRANSFERENCIA] La cantidad a transferir debe ser positiva.")
            return False

        # 2. Realizar las operaciones
        self.saldo -= cantidad
        otra_cuenta.saldo += cantidad
        
        print(f"[TRANSFERENCIA OK] {self.titular} transfirió {cantidad:.2f} {self.moneda} a {otra_cuenta.titular}.")
        return True


print("--- 2. Creación de Cuentas ---")

cuenta1 = CuentaBancaria("ES1234567890", "Juan Pérez", 1000.00)
cuenta2 = CuentaBancaria("ES0987654321", "María López", 500.00)

print("\n--- 3. Realizar depósitos y retirar dinero ---")

cuenta1.depositar(200.50)
cuenta2.depositar(50.00)


cuenta1.retirar(100.00)
cuenta2.retirar(600.00) # Esto debería fallar

print("\n--- 4. Transferir dinero de una cuenta a otra ---")

monto_transferencia = 300.00
cuenta1.transferir(cuenta2, monto_transferencia)

cuenta1.transferir(cuenta2, 900.00)

print("\n--- 5. Imprimir el saldo de ambas cuentas después de la transferencia ---")
print(f"Saldo final de {cuenta1.titular}: {cuenta1.obtener_saldo():.2f} {cuenta1.moneda}") 
print(f"Saldo final de {cuenta2.titular}: {cuenta2.obtener_saldo():.2f} {cuenta2.moneda}")

--- 2. Creación de Cuentas ---

--- 3. Realizar depósitos y retirar dinero ---
[DEPÓSITO OK] Saldo de Juan Pérez (N° 7890) aumentado en 200.50 EUR.
[DEPÓSITO OK] Saldo de María López (N° 4321) aumentado en 50.00 EUR.
[RETIRO OK] Juan Pérez retiró 100.00 EUR. Saldo restante: 1100.50 EUR.
[ERROR RETIRO] Fondos insuficientes para María López. Saldo actual: 550.00 EUR.

--- 4. Transferir dinero de una cuenta a otra ---
[TRANSFERENCIA OK] Juan Pérez transfirió 300.00 EUR a María López.
[ERROR TRANSFERENCIA] Juan Pérez no tiene suficientes fondos para transferir 900.00 EUR.

--- 5. Imprimir el saldo de ambas cuentas después de la transferencia ---
Saldo final de Juan Pérez: 800.50 EUR
Saldo final de María López: 850.00 EUR

## Ejercicio 48
Somos una empresa que tiene varias tiendas de electrodomésticos. Necesitamos un programa para manejar las tiendas, ver las ventas que han tenido, cuántos empleados hay, etc... Para ello vamos a modelizar la tienda en una clase, que tendrá las siguientes características:
* Nombre clase: "Tienda"
* Atributos comunes:
    * Tipo: "Electrodomésticos"
    * Abierta: True
* Atributos propios de cada tienda:
    * Nombre - String
    * Dirección - String
    * Número de empleados - int
    * Ventas últimos 3 meses - Lista de 3 numeros
* Método para calcular las ventas de todos los meses, que devuelva un número con todas las ventas.
* Método que calcula la media de ventas de los últimos meses, por empleado
* Método que devuelve en un string el nombre de la tienda, junto con su dirección.
* Método que obtiene las ventas del último mes.
* Método para dar una proyección de las ventas en caso de haber invertido X dinero en marketing en esa tienda. Siendo X el parámetro de entrada. Si X es menor de 1000, las ventas de los ultimos 3 meses hubiesen sido de (1.2 x ventas), si es mayor o igual de 1000, las ventas hubiesen sido de (1.5 x venta). El método reescribe el atributo de ventas en los últimos 3 meses, y además devuelve las ventas con el aumento.

Se pide:
1. Implementar la clase "Tienda"
2. Crear tres tiendas con datos inventados
3. Comprueba en al menos una de ellas, todo lo implementado en la clase tienda (sus atributos, media de ventas, ventas/empleado...)
3. Calcular las ventas del último mes de todas las tiendas. Para ello usa el bucle `for`
4. Imprime por pantalla los nombres de las tiendas cuya dirección lleve el string "Avenida"
5. Seguro que ya has hecho este apartado... Documenta la clase :)

In [79]:
class Tienda:
    """
    Representa una tienda de electrodomésticos con sus métricas de ventas.
    """

    tipo = "Electrodomésticos"
    abierta = True

    def __init__(self, nombre: str, direccion: str, num_empleados: int, ventas_3m: list):
        """
        Inicializa una nueva instancia de Tienda.

        Args:
            nombre (str): Nombre de la tienda.
            direccion (str): Dirección física de la tienda.
            num_empleados (int): Número de empleados.
            ventas_3m (list): Lista de 3 floats/ints con las ventas de los últimos 3 meses.
        """
        self.nombre = nombre
        self.direccion = direccion
        self.num_empleados = num_empleados
        self.ventas_3m = ventas_3m

    def ventas_totales(self) -> float:
        """Calcula y devuelve la suma total de las ventas de los últimos 3 meses."""
        return sum(self.ventas_3m)
    
    def media_ventas_por_empleado(self) -> float:
        """Calcula la media de ventas totales por empleado."""
        if self.num_empleados == 0:
            return 0.0  # Evita la ZeroDivisionError
        return self.ventas_totales() / self.num_empleados
    
    def obtener_resumen(self) -> str:
        """Devuelve un string con el nombre y la dirección de la tienda."""
        return f"Tienda: {self.nombre} | Dirección: {self.direccion}"
    
    def ventas_ultimo_mes(self) -> float:
        """Obtiene las ventas del último mes (último elemento de la lista)."""
        if not self.ventas_3m:
            return 0.0
        return self.ventas_3m[-1]
        
    def proyectar_ventas(self, inversion_marketing: float) -> list:
        """
        Proyecta y actualiza las ventas de los últimos 3 meses basándose en una inversión en marketing.
        
        Args:
            inversion_marketing (float): Cantidad invertida en marketing.

        Returns:
            list: Lista de las ventas proyectadas (actualizado como atributo).
        """
        if inversion_marketing < 1000:
            incremento = 1.2
        else:
            incremento = 1.5

        ventas_proyectadas = [venta * incremento for venta in self.ventas_3m]
        # LO MISMO SERÍA:
        # ventas_proyectadas = []  # Inicializas una lista vacía
        # for venta in self.ventas_3m:
        #     resultado = venta * incremento
        #     ventas_proyectadas.append(resultado)
        
        # Reescribe el atributo
        self.ventas_3m = ventas_proyectadas
        return self.ventas_3m


print("--- 2. Creación de Tres Tiendas ---")

tienda_a = Tienda("Central Chamberí", "Calle Alcalá 25", 5, [15000.0, 18000.0, 22000.0])
tienda_b = Tienda("Outlet Las Rosas", "Avenida de América 100", 3, [8000.0, 9500.0, 7000.0])
tienda_c = Tienda("Tienda Moncloa", "Avenida Principal 33", 4, [12000.0, 14000.0, 16000.0])

flota_tiendas = [tienda_a, tienda_b, tienda_c]


print("\n--- 3. Comprobar todos los métodos de una tienda (Tienda A) ---")
print(f"Nombre y Dirección: {tienda_a.obtener_resumen()}")
print(f"Tipo (Común): {tienda_a.tipo}")
print(f"Total Ventas: {tienda_a.ventas_totales():.2f}€")
print(f"Media/Empleado: {tienda_a.media_ventas_por_empleado():.2f}€")
print(f"Ventas Último Mes: {tienda_a.ventas_ultimo_mes():.2f}€")

inversion = 2500
print(f"\nProyección de Ventas (Inversión: {inversion}€):")
ventas_proy = tienda_a.proyectar_ventas(inversion)
print(f"Ventas proyectadas: {ventas_proy}")
print(f"Nuevas Ventas Totales: {tienda_a.ventas_totales():.2f}€ (Atributo actualizado)")


print("\n--- 4. Calcular las ventas del último mes de todas las tiendas ---")
for tienda in flota_tiendas:
    print(f"Ventas de '{tienda.nombre}' (Último Mes): {tienda.ventas_ultimo_mes():.2f}€")


print("\n--- 5. Imprime nombres de tiendas cuya dirección lleve el string 'Avenida' ---")
for tienda in flota_tiendas:
    if "avenida" in tienda.direccion.lower(): 
        print(f"Tienda con 'Avenida': {tienda.nombre}")

print("\n--- 5. Documentación de la clase ---")
print("La documentación (docstrings) ha sido incluida dentro de la definición de la clase y sus métodos.")

--- 2. Creación de Tres Tiendas ---

--- 3. Comprobar todos los métodos de una tienda (Tienda A) ---
Nombre y Dirección: Tienda: Central Chamberí | Dirección: Calle Alcalá 25
Tipo (Común): Electrodomésticos
Total Ventas: 55000.00€
Media/Empleado: 11000.00€
Ventas Último Mes: 22000.00€

Proyección de Ventas (Inversión: 2500€):
Ventas proyectadas: [22500.0, 27000.0, 33000.0]
Nuevas Ventas Totales: 82500.00€ (Atributo actualizado)

--- 4. Calcular las ventas del último mes de todas las tiendas ---
Ventas de 'Central Chamberí' (Último Mes): 33000.00€
Ventas de 'Outlet Las Rosas' (Último Mes): 7000.00€
Ventas de 'Tienda Moncloa' (Último Mes): 16000.00€

--- 5. Imprime nombres de tiendas cuya dirección lleve el string 'Avenida' ---
Tienda con 'Avenida': Outlet Las Rosas
Tienda con 'Avenida': Tienda Moncloa

--- 5. Documentación de la clase ---
La documentación (docstrings) ha sido incluida dentro de la definición de la clase y sus métodos.

## Ejercicio 49
En este ejercicio vamos a implementar una clase *Perro* en Python. La clase tiene las siguientes características:
* Cosas que sabemos seguro que tiene un perro
    * Tiene 4 patas
    * 2 orejas
    * 2 ojos
    * Una velocidad de 0. Por defecto, el perro está parado
* Cuando se inicialice:
    * El perro será de una determinada raza
    * Por defecto tendrá pelo "Marrón", a no ser que se diga lo contrario.
    * Por defecto no tendrá dueño, a no ser que se diga lo contrario.
    
* Dispondrá también de un método llamado andar, que tiene un argumento de entrada (aumento_velocidad). Este valor se le sumará a la velocidad que ya llevaba el perro.
* Necesita otro método (parar), donde pondremos la velocidad a 0.
* Otro método llamado "ladrar", que tendrá un argumento de entrada, y la salida será el siguiente string: "GUAU!" + el argumento de entrada.


Se pide:
* Implementa la clase *Perro*
* Crea un objeto de tipo *Perro*, sin dueño
* Comprueba que están bien todos sus atributos
* Prueba que ande, y comprueba su velocidad
* Páralo
* Documenta la clase *Perro*

In [80]:
class Perro:
    patas = 4
    orejas = 2
    ojos = 2

    def __init__(self, raza: str, pelo: str = "Marrón", dueño: bool = False):
        """
        Inicializa un nuevo perro.

        Args:
            raza (str): La raza del perro.
            pelo (str, optional): El color del pelo. Por defecto, "Marrón".
            dueño (bool, optional): Indica si el perro tiene dueño. Por defecto, False.
        """
        self.pelo = pelo
        # Se renombra 'owner' a 'dueño' para mantener consistencia con el enunciado
        self.dueño = dueño 
        self.raza = raza
        # Velocidad inicial propia de este perro (Atributo de Instancia)
        self.velocidad = 0 

    def andar(self, aumento_velocidad: float):
        """
        Aumenta la velocidad del perro.

        Args:
            aumento_velocidad (float): El valor a sumar a la velocidad actual.
        """
        self.velocidad += aumento_velocidad

    def parar(self):
        """
        Pone la velocidad del perro a cero.
        """
        self.velocidad = 0

    def ladrar(self, mensaje: str) -> str:
        """
        Devuelve el sonido del ladrido concatenado con un mensaje.

        Args:
            mensaje (str): El argumento de entrada a concatenar.
            
        Returns:
            str: El ladrido con el mensaje.
        """
        # Se ajusta la salida para que coincida con el formato del enunciado
        return f"GUAU! {mensaje}"

In [82]:
print("\n--- Creación y Verificación ---")

perro1 = Perro(raza="Golden Retriever", dueño=False) 

print(f"Raza: {perro1.raza}")
print(f"Pelo por defecto: {perro1.pelo}")
print(f"Tiene dueño: {perro1.dueño}")
print(f"Patas (Atributo de Clase): {Perro.patas}")
print(f"Velocidad inicial: {perro1.velocidad}")
print(f"Ladrar: {perro1.ladrar('¡Hola!')}")

print("\n--- Prueba de Movimiento ---")

aumento = 5.5
perro1.andar(aumento)
print(f"El perro ha andado, velocidad actual: {perro1.velocidad}")

perro1.parar()
print(f"El perro ha parado, velocidad actual: {perro1.velocidad}")

--- Creación y Verificación ---
Raza: Golden Retriever
Pelo por defecto: Marrón
Tiene dueño: False
Patas (Atributo de Clase): 4
Velocidad inicial: 0
Ladrar: GUAU! ¡Hola!

--- Prueba de Movimiento ---
El perro ha andado, velocidad actual: 5.5
El perro ha parado, velocidad actual: 0

## Ejercicio 50
Importa el módulo de `numpy` y obtén su versión.

In [89]:
import numpy as np
np.__version__

'2.0.1'

## Ejercicio 51
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [90]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]

## Ejercicio 52
Crea un array 3x3, que sea todo a True

In [91]:
array_true = np.full((3,3),True)
array_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 53
Extrae todos los impares de `my_array`

In [94]:
for num in my_array:
    if num%2 != 0:
        print(num)

1
3
5
7
9

In [95]:
my_array[1::2]
my_array[0::2]

array([0, 2, 4, 6, 8])

## Ejercicio 54
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [100]:
new_array = my_array.copy()
for ind, num in np.ndenumerate(my_array):
    if num%2 != 0:
        new_array[ind] = -1
print(new_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]

In [101]:
new_array2 = my_array.copy()
new_array2[1::2]=-1
new_array2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 55
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [102]:
nuevo_array = my_array.copy()
# condicion = (nuevo_array) %2 != 0 
np.where(nuevo_array %2 != 0 , -1, nuevo_array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 56
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [103]:
my_array.shape

(10,)

In [104]:
my_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Ejercicio 57. Te animas a investigar Pandas???

### Paso 1. Importa librerías necesarias:

numpy as np

pandas as pd

In [105]:
import numpy as np
import pandas as pd

### Paso 2. Lee el data set del siguiente [enlace](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

Pista: guarda la ruta del enlace en una variable, indica el separador que tenga (",", "|", ";", etc).

Lee el dataset con: "pd.read_csv" y en los argumentos le pasas la ruta.

In [106]:
path = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
sep = "|" 
header = 0 # opcional
index = 0 # opcional
pd.read_csv(path, sep=sep, header=header, index_col= index)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Paso 3. Asigna el dataset a una variable y usa el user_id como índice y la primera línea como header.

In [107]:
# users = pd.read_csv(path, sep=sep, header=header, index_col= index)
users = pd.read_csv(path, sep=sep)
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Paso 4. Muestra por pantalla las primeras 25 filas. 
Resuélvelo de 2 formas distintas: con slicing y con método. 

Lo que no sepas, investígalo! el Slicing es SUPERIMPORTANTE.

In [108]:
users[:25]

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

In [109]:
users.iloc[0:25]

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

In [110]:
users.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Paso 5. Muestra las últimas 10 entradas.
Usa: método y slicing.

In [111]:
users.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Paso 6. Qué número de muestras (filas) tiene este dataset?
Resuelve de 2 formas distintas -o las que encuentres! :) -

In [112]:
len(users)

943

In [113]:
users.shape[0]

943

### Paso 7. Cuántas columnas tiene el dataset?
También: de 2 formas.

In [115]:
users.shape[1]

5

In [116]:
users.count(axis='columns')

0      5
1      5
2      5
3      5
4      5
      ..
938    5
939    5
940    5
941    5
942    5
Length: 943, dtype: int64

### Paso 8. Muestra por pantalla el nombre de las columnas.

In [117]:
users.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Paso 9. Qué tipo de dato tiene cada columna?

Resuelvelo de 2 formas

In [118]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

In [119]:
users.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Paso 10. Muestra solamente la columna de oocupation.

Muestralo de 2 formas.

In [120]:
users.iloc[:, 2]

0      M
1      F
2      M
3      M
4      F
      ..
938    F
939    M
940    M
941    F
942    M
Name: gender, Length: 943, dtype: object

In [121]:
users['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Paso 11. Cuántas ocupaciones distintas hay en el dataset? Cuántos usuarios por ocupación hay en el dataset?

In [122]:
len(users['occupation'].value_counts())

21

In [123]:
users['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Paso 12. Cuál es la ocupación más frecuente?

In [124]:
(users['occupation'].value_counts()).max()

196

### Paso 13, Encuentra la función que resume el dataset.

In [125]:
users.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Paso 14. Resume las columnas.

In [126]:
users.describe(include='all')

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Paso 15. Cuál es la edad media de los usuarios?

In [127]:
users['age'].mean()

np.float64(34.05196182396607)

### Paso 16. Cuál es la edad que aparece menos veces?

Tienes varias formas de averiguarlo. Intenta las que encuentres.

In [128]:
edades = users.loc[:, 'age'].value_counts()

In [129]:
minimo=edades.min()

In [130]:
mascara= edades == minimo

In [131]:
edades.loc[mascara].index

Index([7, 11, 66, 10, 73], dtype='int64', name='age')